- name: Create /etc/ssl/crls
  file: path=/etc/ssl/crls state=directory owner=root group=root mode=0755
  tags:
    - tls

- name: Install our TLS files
  copy: content="{{lookup('file', tls_directory + '/' + item.local)}}" dest=/etc/ssl/{{item.remote}} owner=root group=ssl-cert mode={{item.mode}}
  with_items:
    - { local: 'ca.crt.pem', remote: 'certs/{{ server_name }}.{{ domain_name}}_CA.pem', mode: '0644' }
    - { local: 'server.crt.pem', remote: 'certs/{{ server_name }}.{{ domain_name }}.pem', mode: '0644' }
    - { local: 'server.key.pem', remote: 'private/{{ server_name }}.{{ domain_name }}.key', mode: '0640' }
    - { local: 'dhparam.pem', remote: 'dhparam.pem', mode: '0644' }
    - { local: 'crl.pem', remote: 'crls/{{ server_name }}.{{ domain_name }}.crl', mode: '0644' }
# Commenting out: these handlers may not exist if the following services are not
# activated
#  notify:
#    - restart openvpn
#    - restart postfix
#    - restart nginx
#    - restart dovecot
#    - restart prosody
# Do this rather, and can be reused from these services' plays:
  register: tls_files
  tags:
    - tls

- name: Install additional domains TLS files (certificates)
  copy: content="{{lookup('file', tls_directory + '/' + item[0] + item[1])}}" dest=/etc/ssl/certs/{{item[0]}}{{item[1]}} owner=root group=ssl-cert mode=0644
  when: tls_additional_domains is defined
  with_nested:
    - "{{ tls_additional_domains }}"
    - [ '.ca.crt.pem', '.cert.crt.pem'  ]
  tags:
    - tls

- name: Install additional domains TLS files (chain)
  copy: content="{{lookup('file', tls_directory + '/' + item + '.cert.crt.pem')}}\n{{lookup('file', tls_directory + '/' + item + '.ca.crt.pem')}}" dest=/etc/ssl/certs/{{item}}.chain.pem owner=root group=ssl-cert mode=0644
  when: tls_additional_domains is defined
  with_items: "{{ tls_additional_domains }}"
  tags:
    - tls

- name: Install additional domains TLS files (keys)
  copy: content="{{lookup('file', tls_directory + '/' + item + '.key.pem')}}" dest=/etc/ssl/private/{{item}}.key.pem owner=root group=ssl-cert mode=0640
  when: tls_additional_domains is defined
  with_items: "{{ tls_additional_domains }}"
  tags:
    - tls

