- set_fact:
    current_letsencrypt_domain: "{{item.name}}"
    current_letsencrypt_aliases: "{{item.aliases|default([])}}"
  tags: letsencrypt

- name: Generate certificate for current domain (no aliases)
  command: certbot certonly --standalone --preferred-challenges http-01 --email {{ admin_email }} -d {{ current_letsencrypt_domain }} --agree-tos --expand --keep --pre-hook "/bin/run-parts --exit-on-error /etc/letsencrypt/caislean-pre-hooks" --post-hook "/bin/run-parts /etc/letsencrypt/caislean-post-hooks" --non-interactive
  when: current_letsencrypt_aliases == []
  tags: letsencrypt

- name: Generate certificate for current domain (with aliases)
  command: certbot certonly --standalone --preferred-challenges http-01 --email {{ admin_email }} -d {{ current_letsencrypt_domain }},{{current_letsencrypt_aliases|join(',')}} --agree-tos --expand --keep --pre-hook "/bin/run-parts --exit-on-error /etc/letsencrypt/caislean-pre-hooks" --post-hook "/bin/run-parts /etc/letsencrypt/caislean-post-hooks" --non-interactive
  when: current_letsencrypt_aliases != []
  tags: letsencrypt

