- set_fact:
    current_letsencrypt_domain: "{{item.name}}"
    current_letsencrypt_aliases: "{{item.aliases|default([])}}"
  tags: letsencrypt

- name: Configure nginx to use LE certificate
  template:
    src: letsencrypt.j2
    dest: "/etc/nginx/includes/{{current_letsencrypt_domain}}/letsencrypt"
    owner: root
    group: root
    mode: 0644
  tags: letsencrypt
  notify:
    - restart nginx

- name: Make sure nginx does not use TLS configuration used from role tls
  file: path=/etc/nginx/includes/{{current_letsencrypt_domain}}/tls-{{current_letsencrypt_domain}} state=absent
  tags: letsencrypt
  notify:
    - restart nginx

- name: Generate certificate for current domain (no aliases)
  command: certbot certonly --standalone --preferred-challenges http-01 --email {{ admin_email }} -d {{ current_letsencrypt_domain }} --agree-tos --keep --pre-hook "/usr/sbin/service nginx stop" --post-hook "/usr/sbin/service nginx start" --non-interactive
  when: current_letsencrypt_aliases == []
  tags: letsencrypt

- name: Generate certificate for current domain (with aliases)
  command: certbot certonly --standalone --preferred-challenges http-01 --email {{ admin_email }} -d {{ current_letsencrypt_domain }},{{current_letsencrypt_aliases|join(',')}} --agree-tos --keep --pre-hook "/usr/sbin/service nginx stop" --post-hook "/usr/sbin/service nginx start" --non-interactive
  when: current_letsencrypt_aliases != []
  tags: letsencrypt

