- fail: msg="Only Debian Jessie is supported by this role."
  when: ansible_distribution_release != "jessie"
  tags: letsencrypt

- name: Install certbot letsencrypt client
  apt: pkg=certbot state=installed default_release={{ansible_distribution_release}}-backports
  tags: letsencrypt

- name: Create custom hooks directories for letsencrypt
  file: path=/etc/letsencrypt/{{item}} state=directory owner=root group=root mode=0755
  with_items:
    - 'caislean-pre-hooks'
    - 'caislean-post-hooks'
  tags: letsencrypt

- name: Generate list of domains we have a service set up for and want a Let's Encrypt certificate
  set_fact:
    letsencrypt_services: "{{letsencrypt_services|default([]) + [item.name]}}"
  with_items: "{{websites|default([])}}"
  when: (item.letsencrypt|default(True)) and (item.name not in (tls_additional_domains|default([])))
  tags: letsencrypt

- name: Generate list of all wanted Let's Encrypt domains
  set_fact:
    all_letsencrypt_domains: "{{(additional_letsencrypt_domains|default([]) + letsencrypt_services) | unique}}"
  tags: letsencrypt

- include: letsencrypt.yml
  with_items: "{{all_letsencrypt_domains}}"

- name: Remove lets encrypt nginx configuration for domains where it is not wanted
  file: path=/etc/nginx/includes/{{item.name}}/letsencrypt state=absent
  with_items: "{{websites|default([])}}"
  when: ((item.letsencrypt|default(True)) == False) or (item.name in (tls_additional_domains|default([])))
  tags: letsencrypt
  notify:
    - restart nginx

- name: Schedule certificates renewal using cron
  cron:
    name: renew letsencrypt certificates
    job: certbot renew --standalone --pre-hook "/bin/run-parts --exit-on-error /etc/letsencrypt/caislean-pre-hooks" --post-hook "/bin/run-parts /etc/letsencrypt/caislean-post-hooks"
    cron_file: caislean_letsencrypt_cert_renewal
    state: present
    special_time: daily
    user: root
  tags: letsencrypt
